apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: default
spec:
  containers:
  - name: kafka-producer
    image: confluentinc/cp-kafka:5.2.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"